### ISSUE TITLE
Database script for RNA isn't labelling NTC variants correctly

### ISSUE THREAD

**Issue by erikwaskiewicz** [AWGL/TSO500_post_processing#2]
NTC variants are appended to sample variants list, rather than labelling whether each sample variant has been seen in the NTC

https://github.com/AWGL/TSO500_post_processing/blob/0f9650bccd03861f4f1b86fe692ee1ab9d892eec/fusions_check_with_ntc.py#L72

**Comment by christianfiles** [comment]
Removed the create_final_df function and instead added extra code to the format_fusions function, which compares the two files and changes column in_ntc to true if it is also seen in the ntc file.
