### ISSUE TITLE
SAV indexing tab not working for NovaSeq data

### ISSUE THREAD

**Issue by erikwaskiewicz** [AWGL/TSO500_post_processing#7]
This tab is used to compare the relative amount of reads in different samples across the run. A script has been developed to replicate these plots and needs reviewing and adding to the pipeline.

Script should be added after demultiplexing in `1_TSO500.sh`

**Comment by christianfiles** [comment]
read_count_visualisation.py has been added to this location; /data/diagnostics/scripts/

The following line has been added to the 1_TSO500.sh script so should now produce these graphs automatically once pulled across to the master branch;
`python /data/diagnostics/scripts/read_count_visualisation.py`
